### ISSUE TITLE
Inspection findings report

### ISSUE THREAD

**Issue by Christdej** [equinor/flotilla#1049]
**Describe the new feature you would like to see**
After the robot has completed a mission, or at certain intervals, Flotilla should create a report about potential findings from the mission / time period and report it to whoever is interested. 

**Describe the solution you'd like**
We need to store the report in the database in some form, probably not the data itself, but links to where the data can be found.

The task is further divided into following issues:

- [x] Period Report generation: https://github.com/equinor/flotilla/issues/1102

- [x] Endpoint for updates from Analytic(s) pipeline: https://github.com/equinor/flotilla/issues/1103

- [x] Inspection reportng over Teams: https://github.com/equinor/flotilla/issues/1104

- [x] Storing inspection findings in database: https://github.com/equinor/flotilla/issues/1105

- [x] [Refactor inspectionFinding post call to include isarStepId in the path and refactor the InspectionFindings model as well.#1186]

**Comment by UsamaEquinorAFK** [comment]
What does the word report entails here ? Are these inspection links to the media collected in vendor cloud or our blob storage ?

**Comment by UsamaEquinorAFK** [comment]
Period Report generation: 
https://github.com/orgs/equinor/projects/85/views/4?pane=issue&itemId=43329779

**Comment by UsamaEquinorAFK** [comment]
Improvement: flotilla #1231

**Comment by UsamaEquinorAFK** [comment]
Improvements 
#1318
#1296

**Comment by UsamaEquinorAFK** [comment]
Completed main parts now improvements will be handled separately independent of epic
